program: sweep_train.py
method: random
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "train"
  - "-f"
  - "configs/claim_target_identification_bert_base_uncased.jsonnet"
  - "-s"
  - "experiment/hpt/task1/bert-base-uncased"
  - ${args}

metric:
  name: validation_accuracy
  goal: maximize
parameters:

  trainer.optimizer.lr:
    values: [0.1, 0.05,0.03,0.01,0.005,0.003,0.001,0.0005,0.0003,0.0001,0.00003,0.00001,0.000003,0.000001]
  trainer.grad_norm:
    distribution: uniform
    min: 1
    max: 10
  trainer.patience:
    min: 2
    max: 7
  trainer.num_epochs:
    min: 1
    max: 30
  model.dropout:
    distribution: uniform
    min: 0.1
    max: 0.6
  model.encoder.dropout:
    distribution: uniform
    min: 0.1
    max: 0.8