program: sweep_train.py
method: random
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "train"
  - "-f"
  - "configs/claim_sentiment_classification.jsonnet"
  - "-s"
  - "experiment/sentiment/hpt_trial/distilbert_base"
  - "--include-package"
  - "readers.SentDataReader"
  - ${args}

metric:
  name: validation_accuracy
  goal: maximize
parameters:

  trainer.optimizer.lr:
    values: [0.1, 0.05,0.03,0.01,0.005,0.003,0.001,0.0005,0.0003,0.0001,0.00003,0.00001,0.000003,0.000001]
  model.dropout:
    distribution: uniform
    min: 0.2
    max: 0.8
  model.seq2vec_encoder.dropout:
    distribution: uniform
    min: 0.2
    max: 0.8
  trainer.grad_norm:
    distribution: uniform
    min: 1
    max: 10
  trainer.patience:
    min: 3
    max: 10
  trainer.num_epochs:
    min: 4
    max: 30
  model.seq2vec_encoder.num_layers:
    min: 1
    max: 6
  model.seq2vec_encoder.hidden_size:
    min: 64
    max: 512